Formatting fix for command
mattermost/mattermost-plugin-autolink pull request #153
Opened 2021-03-27 01:01 UTC by bbodenmiller

#### Summary

#### Ticket Link

2021-03-27 01:01 UTC, mattermod commented
Hello @bbodenmiller,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-03-28 07:56 UTC, hanzei requested changes
Good catch! Would you be open on also updating the Usage test in the following table?

2021-03-28 22:32 UTC, levb approved these changes

2021-04-03 02:25 UTC, bbodenmiller commented
@hanzei updated

2021-04-05 06:28 UTC, hanzei approved these changes
Awesome :tada:

2021-04-05 06:28 UTC, merged